version: "2.1"
services:
  omniedge:
    image: omniedge
    build:
      context: .
      dockerfile: ../omniedge/Dockerfile
    container_name: omniedge
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      - OMNIEDGE_SECURITYKEY=OMNIEDGE_SECURITYKEY
      - OMNIEDGE_VIRUTALNETWORK_ID=OMNIEDGE_VIRUTALNETWORK_ID
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:                                             
      - net_admin

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PASSWORD=password #optional
      - HASHED_PASSWORD= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
      - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 8443:8443
    restart: unless-stopped
  