version: "2.1"
services:
  omniedge:
    image: omniedge
    build:
      context: .
      dockerfile: ../omniedge/Dockerfile
    container_name: omniedge
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      - OMNIEDGE_SECURITYKEY=OMNIEDGE_SECURITYKEY
      - OMNIEDGE_VIRUTALNETWORK_ID=OMNIEDGE_VIRUTALNETWORK_ID
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:                                             
      - net_admin

  openvscode-server:
    image: lscr.io/linuxserver/openvscode-server:latest
    container_name: openvscode-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CONNECTION_TOKEN= #optional
      - CONNECTION_SECRET= #optional
      - SUDO_PASSWORD=password #optional
      - SUDO_PASSWORD_HASH= #optional
    volumes:
      - /path/to/appdata/config:/config
    ports:
      - 3000:3000
    restart: unless-stopped