version: "2.1"
services:
  omniedge:
    image: omniedge
    build:
      context: .
      dockerfile: ../omniedge/Dockerfile
    container_name: omniedge
    privileged: true
    network_mode: host
    restart: unless-stopped
    environment:
      - OMNIEDGE_SECURITYKEY=OMNIEDGE_SECURITYKEY
      - OMNIEDGE_VIRUTALNETWORK_ID=OMNIEDGE_VIRUTALNETWORK_ID
    volumes:
      - /dev/net/tun:/dev/net/tun
    cap_add:                                             
      - net_admin

  nextcloud:
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /path/to/appdata:/config
      - /path/to/data:/data
    ports:
      - 443:443
    restart: unless-stopped